# Copyright 2017 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""LongKB vnfcluster

Revision ID: 756ba16e0d18
Revises: 0ae5b1ce3024
Create Date: 2017-05-10 23:42:14.908166

"""

# revision identifiers, used by Alembic.
revision = '756ba16e0d18'
down_revision = '0ae5b1ce3024'

from alembic import op
import sqlalchemy as sa


from tacker.db import migration

from tacker.db.types import Json

def upgrade(active_plugins=None, options=None):

    op.create_table(
        'vnfclusters',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('vnfd_id', sa.String(length=36), nullable=False),
        sa.Column('active', sa.Integer, nullable=False),
        sa.Column('standby', sa.Integer, nullable=False),
        sa.Column('policy_info', Json),
        sa.Column('status', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB'
    )

    op.create_table(
        'vnfclustermembers',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('cluster_id', sa.String(length=36), nullable=False),
        sa.Column('index', sa.Integer, nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.Column('lb_member_id', sa.String(length=36)),
        sa.Column('vnf_info', Json),
        sa.ForeignKeyConstraint(['cluster_id'], ['vnfclusters.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB'
    )

def downgrade(active_plugins=None, options=None):
    # commands auto generated by Alembic - please adjust! #
    op.drop_table('vnfclustermembers')
    op.drop_table('vnfclusters')
    # end Alembic commands #
